### ISSUE TITLE
Update MathJax to 2.6.x

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-chrome-extension#100]
Update MathJax from 2.4.0 to 2.5.x (whatever x is).

**Comment by mojavelinux** [comment]
We'll need to verify that no additional settings are needed. I saw an
alignment issue when trying to upgrade the reveal.js backend. Might have
been an issue with reveal.js styles, but gives me reason to check.

**Comment by tribut** [comment]
Mathjax before v2.6 have a rendering issue on reasonably recent versions of Chrome (see [Chrome issue](https://code.google.com/p/chromium/issues/detail?id=552421), [Mathjax issue](https://github.com/mathjax/MathJax/issues/1300)). I would very much appreciate an update to MathJax v2.6.

**Comment by mojavelinux** [comment]
Definitely. We've moved Asciidoctor core to MathJax 2.6, so we're good to make the move.

**Comment by mojavelinux** [comment]
I updated the title to reflect the change.

**Comment by Mogztter** [comment]
Thanks Dan. Asciidoctor core use MathJax 2.6 or 2.5 ?

**Comment by mojavelinux** [comment]
2.6. See https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L241
