### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by tedbergeron** [asciidoctor/asciidoctor-chrome-extension#104]
Version 1.5.2.111 has stopped working on Windows Chrome Version 42.0.2311.135 m and has stopped working on Linux Chromium.

**Comment by Mogztter** [comment]
On local files ? Or both on local files (file:// URI) and remote files
(http(s):// URI) ?

**Comment by tedbergeron** [comment]
On local files. I only use it to view files like this...  file:///C:/_docs/UsingAsciidoc/Readme.txt

**Comment by Mogztter** [comment]
And do you get an error ?

**Comment by tedbergeron** [comment]
There is no error. The document just displays as text.

I just unchecked and rechecked the Allow access to file URLs option and that solved it in Windows Chrome. 

Thanks.

**Comment by Mogztter** [comment]
We could maybe listen to the `onInstalled` event to display this reminder... https://developer.chrome.com/extensions/runtime#event-onInstalled

I don't know when Google is going to fix this issue but it's really annoying for extensions that rely heavy on this option :disappointed:

**Comment by Mogztter** [comment]
https://code.google.com/p/chromium/issues/detail?id=365107
> Somehow the local files permission is not granted when then extension starts the first time after an update

Maybe calling `reload` can solve the problem: https://developer.chrome.com/extensions/runtime#method-reload

I will do some testing to see if I can workaround this issue

**Comment by tedbergeron** [comment]
I did try to reload the the file. I even closed Chrome and restarted it. Neither worked.
