### ISSUE TITLE
german umlaut in section header not working (dblatex pdf output)

### ISSUE THREAD

**Issue by tobiasd** [asciidoctor/asciidoctor-chrome-extension#105]
Just trying out asciidoc and ran into the following problem:  When a section header contains a german umlaut dblatex quits with an error message and the pdf is not generated. Umlaute in paragraphs cause no problems. Also generation epubs from the same source works fine.

Here is a minimal example
```asciidoc
A Test
======
:author: The Author

Eine Überschrift
----------------

Und ein Text, äöü.
```

Compiling it with ``a2x -f pdf test.txt`` gives this error message:
```
a2x: ERROR: "dblatex" -t pdf -p "/etc/asciidoc/dblatex/asciidoc-dblatex.xsl" -s "/etc/asciidoc/dblatex/asciidoc-dblatex.sty"   "/path/to/test.xml" returned non-zero exit status 1
```

This is the content of the XML file generated:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE article PUBLIC "-//OASIS//DTD DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd">
<?asciidoc-toc?>
<?asciidoc-numbered?>

<article lang="en">
<articleinfo>
    <title>A Test</title>
    <author>
        <firstname>The</firstname>
        <surname>Author</surname>
    </author>
    <authorinitials>TA</authorinitials>
</articleinfo>
<section id="_eine_überschrift">
<title>Eine Überschrift</title>
<simpara>Und ein Text, äöü.</simpara>
</section>
</article>
```

When I run the above dblatex call directly the result is:
```
Build the book set list...
Build the listings...
XSLT stylesheets DocBook - LaTeX 2e (0.3.4)
===================================================
Image 'dblatex' not found
Build test.pdf
pdflatex failed
test.aux:25: Missing \endcsname inserted.
test.aux:25: leading text: ...ft}{{1}{1}{Eine �berschrift}{section.1}{}}
Unexpected error occured
Error: pdflatex compilation failed
```

Installed is asciidoc  8.6.9-2, dblatex  0.3.4-2, texlive 2014 on Manjaro Linux.

**Comment by mojavelinux** [comment]
This is the incorrect repository to report this issue. This relates to AsciiDoc Python, which is over here: https://github.com/asciidoc/asciidoc

Fortunately, I still have an answer for you. This was recently documented by @edusantana.

https://groups.google.com/d/msg/asciidoc/M-mbeOJHISI/TT75x5Y4mHEJ

**Comment by tobiasd** [comment]
Oh, sorry; but thanks for the quick reply :+1: workes as advertised!

**Comment by edusantana** [comment]
Yes @tobiasd , and you should add the language to your file:

    :lang: de

If you are writing a book (instead of an article) add it too:

    :doctype: book

Or add them at command line:

    a2x -f pdf -a lang=de -d book --dblatex-opts "-P latex.encoding=utf8 -P latex.babel.language=de" test.txt
