### ISSUE TITLE
Support Following Include Macros

### ISSUE THREAD

**Issue by devunwired** [asciidoctor/asciidoctor-chrome-extension#107]
This tool is a wonderful extension for developing with Asciidoc, especially in situations where you need to be offline. However, there is one thing I find cumbersome. Currently, if a rendered Asciidoc file includes other Asciidoc files via `include::someFile.adoc[]`, those are not rendered as part of the document, but represented as a clickable link to the secondary file.

This makes it difficult to preview documents when the text content is broken down into smaller modules (with each in their own file).

**Comment by devunwired** [comment]
A related issue: if the files included contain custom attribute definitions, those attributes are not expanded since the document where they were defined isn't rendered.

**Comment by mojavelinux** [comment]
The behavior your observing happens when the safe mode is set to "secure". If you set the safe mode on the options page to something other than "secure", then includes will work. I recommend setting it to "unsafe" as the safety checks are not really relevant in the context.

**Comment by devunwired** [comment]
Ah! So much better. @mojavelinux, I owe you a beer.

**Comment by mojavelinux** [comment]
\o/

**Comment by rmpestano** [comment]
Hi guys,

for me include macros are not working in chrome. I'm trying to include a source code file inside code blocks. I set safe mode to unsafe in chrome extension options, here is output in chrome and firefox (which works):

![chromium](https://cloud.githubusercontent.com/assets/1592273/9564267/64b624dc-4e77-11e5-800f-9ffa0755752e.png)

![firefox](https://cloud.githubusercontent.com/assets/1592273/9564274/76e1fffa-4e77-11e5-8609-8453332a5524.png)

I also tried to set safe mode inside adoc file but didnt worked, here is the adoc file:

:icons: font
:toc: right
:numbered:
:sectanchors:
:source-highlighter: coderay
:safe-mode-0:
:safe: 0


= Document Title
Doc Writer <doc@asciidoc.org>
v1.0, 2013-01-01: Initial version


http://asciidoc.org[AsciiDoc^] is a lightweight markup language.

This is the optional preamble (an untitled section body), useful for
writing simple sectionless documents consisting only of a preamble.

NOTE: The abstract, preface, appendix, bibliography, glossary and
index section titles are significant (_specialsections_).


== Section zero

== First section

Document sections start at *level 1* and can nest four levels deep.

* Item 1
* Item 2

[source,java,linenums]
----
public class HelloAsccidoctor {

  public void aMethod(String param) {
    System.out.println("Hello Asciidoctor");	
  }

}

include::hello.java[]
----


== Second section

Document sections start at *level 1* and can nest four levels deep.

* Item 1
* Item 2

[source,ruby]
puts 'Hello, World!'

=== Sub section

Document sections start at *level 1* and can nest four levels deep.

* Item 1
* Item 2

[source,ruby]
puts 'Hello, World!'

**Comment by Mogztter** [comment]
@rmpestano You are saying that this is working in the Firefox Addon but not in the Chrome Extension ?

And the source of your document is:

```
[source,java,linenums]
----
public class HelloAsccidoctor {
  public void aMethod(String param) {
    System.out.println("Hello Asciidoctor");
  }
}

include::hello.java[]
----
````

**Comment by Mogztter** [comment]
I think there a bug on the options page in the Chrome Extension. Could you try to set `Safe mode` to `unsafe` again and click the save button ? Then reload your file.

**Comment by rmpestano** [comment]
Hi @Mogztter,

yes, the problem is with include macro inside code block, in chrome it renders that "link".

I have set unsafe and saved in extension options, I also restarted the browser and checked the unsafe is set. The problem persists.

**Comment by Mogztter** [comment]
You are using `link::` or `include::` ?
The following is working with the Chrome Extension (and at least server safe mode):
```
= Test

[source,java,linenums]
----
public class HelloAsccidoctor {
  public void aMethod(String param) {
    System.out.println("Hello Asciidoctor");
  }
}

include::hello.java[]
----
```

.hello.java
```
public static void hello() {
  System.out.println("Hello");
}
```

![chrome-ext](https://cloud.githubusercontent.com/assets/333276/9564998/7141e05c-4eb7-11e5-98f8-42a95a795451.PNG)

**Comment by rmpestano** [comment]
Hi again, 
i'm using include, tried your sample and it still doesn't, take a look at my config:
![safe](https://cloud.githubusercontent.com/assets/1592273/9565063/55350168-4e90-11e5-90ce-b2423bfa0bfe.png)

![opt](https://cloud.githubusercontent.com/assets/1592273/9565065/5dac40cc-4e90-11e5-89be-8751953df90f.png)

![out](https://cloud.githubusercontent.com/assets/1592273/9565068/61b2b64c-4e90-11e5-9fbc-aa4c5a5077a1.png)

**Comment by rmpestano** [comment]
I'm using the zip from here: https://github.com/asciidoctor/asciidoctor-chrome-extension/releases/tag/v1.5.2.111

**Comment by rmpestano** [comment]
Oww it works on safe mode here too, sorry for the confusion but I thought it should work in UNSAFE mode. thanks for your time

**Comment by mojavelinux** [comment]
It should work with unsafe too. But safe is actually the recommended setting. unsafe actually causes problems in Asciidoctor.js because we haven't enabled all the features that unsafe tries to use. The documentation should recommend "safe" I think.
