### ISSUE TITLE
footnote superscript disrupts leading

### ISSUE THREAD

**Issue by ds26gte** [asciidoctor/asciidoctor-chrome-extension#114]
The footnote superscript (generated by `footnote:[...]`) is just a little too tall, and bulges the leading (distance between consecutive baselines) on the line that it's on.

This happens only when viewing an AsciiDoc file with the Chrome extension. If I convert the same AsciiDoc file using the Asciidoctor backend `html5` to HTML and view the latter, also on Chrome, -- i.e., without going through the extension --, the leading is fine.

**Comment by mojavelinux** [comment]
This was something that was fixed in Asciidoctor 1.5.3. The Chrome extension hasn't yet been upgraded since the Asciidoctor.js 1.5.3 is still pending (for testing the Opal upgrade). Once the default stylesheet is copied over from Asciidoctor core, this issue should be resolved.

**Comment by ds26gte** [comment]
Thanks! That explains the variant behavior.
