### ISSUE TITLE
Single quote in the title is replaced by the encoded html version

### ISSUE THREAD

**Issue by ismail** [asciidoctor/asciidoctor-chrome-extension#118]
I have a sample document like this:

    Foo's bar
    ------------

when rendered the title shows up as `Foo&#8217;s bar`

**Comment by ismail** [comment]
This is with Chrome 48.0.2564.109 on Linux x86-64.

**Comment by Mogztter** [comment]
Hello @ismail 
Indeed I can reproduce this issue. Not sure what I'm doing wrong, I'm using `doctitle` method from Asciidoctor core: https://github.com/asciidoctor/asciidoctor-chrome-extension/blob/master/app/js/renderer.js#L80

````
asciidoctorDocument.$doctitle(Opal.hash({sanitize: true}))
"Foo&#8217;s bar"

asciidoctorDocument.$doctitle()
"Foo&#8217;s bar"
```

I can decode HTML entities with: 
```javascript
var doctitle = asciidoctorDocument.$doctitle(Opal.hash({sanitize: true}));
document.title = $("<div />").html(doctitle).text();
```
@mojavelinux What do you think ?

**Comment by ismail** [comment]
Any chance of getting this fix integrated soon?

**Comment by mojavelinux** [comment]
This is on my list. I'll look into it asap. I have a strong hunch about what needs to happen.

**Comment by mojavelinux** [comment]
Correct, this is currently a missing feature in the `doctitle` function. We need to make sanitize an enum that accepts various types of sanitization (:cdata, :plain, etc). (See https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/document.rb#L629)

What I recommend is to not use the sanitize flag and instead use jQuery or the DOM to strip HTML elements and decode/resolve entities. 

```js
var doctitle = asciidoctorDocument.$doctitle();
var filter = document.createElement('div');
filter.innerHTML = doctitle;
document.title = filter.textContent;
```

That's going to give you perfect results.

**Comment by mojavelinux** [comment]
PR sent.

**Comment by mojavelinux** [comment]
:+1:

**Comment by ismail** [comment]
Thanks!
