### ISSUE TITLE
Cannot get code highlight to work

### ISSUE THREAD

**Issue by tedbergeron** [asciidoctor/asciidoctor-chrome-extension#133]
I tried adding the attribute `:source-highlighter: highlightjs` to my AsciiDoc file but could not make it work. I also tried using the Options: Custom Attributes: source-highlighter=highlightjs.

I see the code is adding the highlight css and js files. So I created a tiny JavaScript file 
`<script>hljs.initHighlighting()</script>` and I used the Options: Add a custom JavaScript to the rendered HTML and selected After the document has been rendered.

This forces the code highlighting to work. I'm not sure if that is what everyone would want. It would be cool if adding the attribute would trigger the code to initialize the highlighter script. Which is probably how you have it working. I just can't get it to work currently. 

I'm using Chrome Version 52.0.2743.116 m

**Comment by Mogztter** [comment]
Hello @tedbergeron 

This should work out of the box. Are you using version 1.5.4.110 ? Could you please provide a sample document that does not work ?

Here's a simple example with Chrome 51 (I will try with Chrome 52)

![highlight-ext](https://cloud.githubusercontent.com/assets/333276/17535723/a3041ee0-5e90-11e6-85ba-7922e6c8124a.png)

**Comment by tedbergeron** [comment]
I just tested this on a different Windows machine and it works as is, like you said.

- Chrome: Version 52.0.2743.116 m
- Win 10
- Asciidoctor 1.5.4

I will take a look at the problem machine to see what is wrong with my Chrome browser. Thank you for the information. Sorry for the false alarm.

**Comment by Mogztter** [comment]
No worries, let me know if you find something :wink:
