### ISSUE TITLE
toc preamble doesn't work

### ISSUE THREAD

**Issue by obilodeau** [asciidoctor/asciidoctor-chrome-extension#139]
Although the README states that `:toc: preamble` should work, it does not. The manual placement syntax works though.

This minimal example doesn't render a ToC:
```
= Minimal test case
:toc: preamble

== One

Yes

== Two

Why not
```

* Version 1.5.5.100
* Chrome 55.0.2883.87

**Comment by Mogztter** [comment]
The documentation does not state this clearly but you do need a preamble otherwise the toc will not shown.


```adoc
= Minimal test case
:toc: preamble

This is a preamble.

== One

Yes

== Two

Why not
```

The important part is "This is a preamble."

**Comment by mojavelinux** [comment]
Correct. The preamble placement should now be considered a specialized use
case since toc (no value) works in all cases (including embeddable HTML,
which is what's used here).

**Comment by obilodeau** [comment]
> The important part is "This is a preamble."

Ahh I see.

> Correct. The preamble placement should now be considered a specialized use
> case since toc (no value) works in all cases (including embeddable HTML,
> which is what's used here).

Confirmed, simply using `:toc:` instead of `:toc: preamble` worked. Which is fine for me. I guess I was confused by the documentation (and I am using `:toc: preamble` on github so I've just copied that).

**Comment by mojavelinux** [comment]
Yep. Docs need updating. I'd be happy to do it if you file an issue.
