### ISSUE TITLE
Link attributes seem not to work

### ISSUE THREAD

**Issue by oncletom** [asciidoctor/asciidoctor-chrome-extension#143]
I am referring to the [link macro](http://asciidoctor.org/docs/asciidoc-writers-guide/#external-links) described in asciidoctor documentation.

When I try to use this syntax, the extension does render the *brackets content* as if it were the *entire text content*:

```
link:http://discuss.asciidoctor.org/[*mailing list*^, role="green"]
```

Renders as:

<img width="236" alt="screen shot 2017-02-14 at 13 27 34" src="https://cloud.githubusercontent.com/assets/138627/22928960/60c8123a-f2b9-11e6-82e8-d54f6b9d9a7b.png">

Instead of:

<img width="123" alt="screen shot 2017-02-14 at 13 30 28" src="https://cloud.githubusercontent.com/assets/138627/22929039/c7ff90e0-f2b9-11e6-9efe-4ddf3c02ad6e.png">

**Comment by Mogztter** [comment]
Thanks for the detailed issue.
It's most likely a RegExp issue in Opal...

The following is working as expected:
```adoc
link:http://discuss.asciidoctor.org/[*mailing list*^]
```

**Comment by Mogztter** [comment]
I can reproduce this issue in Atom.
@mojavelinux I think this is where I should look: https://github.com/asciidoctor/asciidoctor/blob/673500f6103b1e6714026238463a77c51527a8d4/lib/asciidoctor/substitutors.rb#L849-L922 (in Asciidoctor.js) ?

**Comment by mojavelinux** [comment]
You must enable the linkattrs document attribute to use named attributes in
a link macro.

I think there's an open issue to switch this attribute on by default (when
not running in compat mode).

**Comment by oncletom** [comment]
Understood, thanks! 👍

**Comment by mojavelinux** [comment]
Here's the upstream feature: https://github.com/asciidoctor/asciidoctor/issues/2059. I'm interested in your thoughts as a user. Should we just go ahead and enable this by default (when compat mode is not on).

**Comment by oncletom** [comment]
I do not know if this an asciidoctor-only feature and I am not well aware of the options strategy.

But indeed without browsing the doc (and I missed it), I felt it weird I could not add roles on links like I would do on code blocks or admonition for example.

**Comment by mojavelinux** [comment]
That's the input I was looking for. Thanks!
