### ISSUE TITLE
asciimath incorrect output

### ISSUE THREAD

**Issue by iovuio** [asciidoctor/asciidoctor-chrome-extension#149]
**Steps to reproduce**
1. Create document with content
```
= Math formulae

[asciimath]
++++
sum_(i=1)^n i^3=((n(n+1))/2)^2
++++
```
2. Open file in Chrome having asciidoctor-chrome-extension installed.

**Expected result**

  Formula displayed as follows (screenshot taken from mathjax.org)
<img width="193" alt="should" src="https://user-images.githubusercontent.com/1754481/27992131-d7432dd0-6494-11e7-9c82-4591faa0f0c6.png">

**Actual result**

  Formula displayed as follows
<img width="259" alt="is" src="https://user-images.githubusercontent.com/1754481/27992136-0d8e4122-6495-11e7-829d-a98b4991cff7.png">

**Comment by Mogztter** [comment]
@mojavelinux Is this intended ?

**Comment by mojavelinux** [comment]
The Asciidoctor MathJax integration requires a special MathJax configuration block. This appears to be missing from the chrome extension.

See https://github.com/asciidoctor/asciidoctor/blob/911d0bd509f369e9da15d2bb71f81aecb7c45fec/lib/asciidoctor/converter/html5.rb#L224-L245

**Comment by mojavelinux** [comment]
...or it's not loading correctly.

**Comment by mojavelinux** [comment]
The following document works fine with Asciidoctor Ruby.

```
= Math formulae
:stem:

[asciimath]
++++
sum_(i=1)^n i^3=((n(n+1))/2)^2
++++
```

**Comment by mojavelinux** [comment]
I see what it is. It's that the configuration is incorrect. The asciimath delimiters are listed in the tex2jax delimiters, so the expression is being interpreted as latexmath instead of asciimath.

```
inlineMath: [['\\$','\\$'],['\\(','\\)']],
```

**Comment by mojavelinux** [comment]
Yep, that was it. PR on the way.
