### ISSUE TITLE
Remove "Chrome" reference since this code base will be shared between Chrome/Chromium, Firefox, Opera and (hopefully) Edge... Safari ?

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-chrome-extension#168]
To ease the release and publish process on each "store" we should remove "Chrome" reference in the README and manifest.

**Comment by mojavelinux** [comment]
\o/

What do you think about renaming the repository too? Or would that cause too much disruption?

**Comment by Mogztter** [comment]
I've never done that before, so I'm a bit 😨 
Can we configure an automatic redirection between the old name and the new name ?
 https://github.com/asciidoctor/asciidoctor-chrome-extension -> https://github.com/asciidoctor/asciidoctor-browser-extension

I'm asking because otherwise I need to update the URL of the repository on every store 🐙

**Comment by Mogztter** [comment]
According to this page, GitHub should take care of the redirection: https://help.github.com/articles/renaming-a-repository/

**Comment by mojavelinux** [comment]
I've renamed many repositories, so I speak from experience when I say it's totally seamless. Both web traffic and git traffic are automatically redirected to the new repository. So the old name stays valid in case you forget to update it somewhere. And you can update at your leisure.

If you want to proceed, I recommend opening a new issue so we can finalize the name and track the admin task.
