### ISSUE TITLE
include directive does not work

### ISSUE THREAD

**Issue by githorse** [asciidoctor/asciidoctor-chrome-extension#181]
The include directive does work for me -- it just renders a link to the included file, rather than inserting the file itself. (The files are included as expected in a different Asciidoc viewer, so I don't think it's an issue with their syntax.) 

```
= Test Document

Here's an included file:

include::another.adoc[]
```

Output:

<img width="415" alt="screen shot 2017-10-29 at 6 05 25 pm" src="https://user-images.githubusercontent.com/8271372/32148937-e04a46c4-bcd3-11e7-9323-51a1c38767ca.png">

I'm able to click the link to the included file and see it, so it's not a path problem either.

**Comment by Mogztter** [comment]
Could you please check the safe mode in the options page ? You need to set the safe mode to "safe": http://asciidoctor.org/docs/user-manual/#running-asciidoctor-securely

**Comment by githorse** [comment]
That does it! Much obliged.
