### ISSUE TITLE
Support for {indir} and {infile}

### ISSUE THREAD

**Issue by oncletom** [asciidoctor/asciidoctor-chrome-extension#58]
Hello,

according to http://www.methods.co.nz/asciidoc/chunked/ch31.html, there are built-in/dynamic attributes like `{indir}`, which are super handy to know precisely where we are.

I have two issues:
- `{indir}` does not seem to be resolved
- attributes do not seem to be concatenable

``` adoc
# index.adoc
= Book Title
include::chapters/02.adoc[]

# chapters/02.adoc
:imageDir: {indir}/images

image::{imageDir}/sample.png[align="center"]
```

At the moment, if I define `{imageDir}` as `./images`, then it does not resolve the proper path when the `chapter02.adoc` is included, because `{imageDir}/sample.png` is resolved as `images/sample.png` instead of `chapters/images/sample.png`.

**Comment by mlidbom** [comment]
I could really use this feature. I want to create "improve this section" links to github for some documentation that will likely become quite large.
Knowing the path of the current file seems like a requirement for that.

**Comment by mojavelinux** [comment]
@mlidbom Actually, that's already possible. If you enable the sourcemap option when calling the Asciidoctor API, then you can get the file and line number for blocks (including sections). While the content is not aware of what file it is in, the AST is aware. A slight difference, but it fits your use case.

**Comment by mlidbom** [comment]
@mojavelinux Thank you for the tip :)
