### ISSUE TITLE
Support embedded videos (YouTube / Vimeo)

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-chrome-extension#87]
It appears that extra work is required to get embedded YouTube and Vimeo videos to work.

Here's a test page:

https://raw.githubusercontent.com/devoxx4kids/materials/c68d1a51811d7c3ae6b7b29b801b8d04cf7fcbd8/workshops/minecraft/readme.asciidoc

There should be a video on that page. You can see how it should appear through docgist:

http://gist.asciidoctor.org/?github-devoxx4kids%2Fmaterials%2Fc68d1a51811d7c3ae6b7b29b801b8d04cf7fcbd8%2F%2Fworkshops%2Fminecraft%2Freadme.asciidoc

NOTE: The same problem exists in the Firefox Add-on and likely other related tools.

**Comment by Mogztter** [comment]
I will try to use `webview` instead of `iframe` https://developer.chrome.com/apps/tags/webview

**Comment by Mogztter** [comment]
Urgh, onl available in packaged apps and not extension :sob:

**Comment by Mogztter** [comment]
The following code is working... but I'm not really proud:

```javascript
// Refresh iframe
$('iframe').each(function() {
  var src = $(this).attr('src');
  $(this).attr('src',  src);
});
```

**Comment by mojavelinux** [comment]
Sometimes, you gotta do what the situation calls for. If it makes you feel better, you could do it in one line:

```javascript
$('iframe').each(function() { $(this).attr('src', $(this).attr('src')) });
```

Perhaps add a comment above the line that explains why this works?

**Comment by mojavelinux** [comment]
:+1:
