### ISSUE TITLE
Add tip about enabling local file access to options page

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-chrome-extension#92]
New users often forget to tick the `Allow access to file URLs` on the extension page. We should draw more attention to this advice.

Although the options page can't enable access to local files, we could use that screen to remind users about it using a callout (i.e., tip).

It also might be a good idea to draw more attention to this advice in the extension's description in the chrome store. I think we are limited to plain text, but we could surround it with `IMPORTANT!` so it's hard to miss.

**Comment by Mogztter** [comment]
Yes it's a good idea :+1:

**Comment by leif81** [comment]
Good idea.

Could the extension intercept the a `file:///*.adoc` request and display a reminder at that point too? If possible maybe replace the body of the page with the tip.

**Comment by Mogztter** [comment]
@leif81 I don't think so because the main script is not triggered until you enable access to local file :disappointed:
