### ISSUE TITLE
Issue with UNC Shares

### ISSUE THREAD

**Issue by chevdor** [asciidoctor/asciidoctor-chrome-extension#94]
If I try to open a file from a share (UNC path). I get the following message:
```Error
Exception : asciidoctor: FAILED: : Failed to parse source, Cannot read property '$respond_to?' of undefined```

I can open the files just fine when copying them locally on my machine.

**Comment by Mogztter** [comment]
Hi @chevdor, could you put an example URL ?

**Comment by chevdor** [comment]
Sure, I just reproduced the issue again on another machine.
I forgot to mention that it happens on Windows.
I actually tested by sharing a folder and accessing the asciidoc file thru the share.

The URL looks like this:
   file://mycomputer/Shared/test.adoc

**Comment by Mogztter** [comment]
I can reproduce this issue and the underlying error is:

`XMLHttpRequest cannot load file://mogzbox/Users/ggrossetie/Downloads/test.adoc?_=1425810273171. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.`

AFAIK the only options are to setup a webserver or to copy the file to your local disk :disappointed:

**Comment by chevdor** [comment]
Oh I see. I will add options then although none is really cool but I doubt you can change anything about it.
I guess mapping the share would help or running Chrome with --disable-web-security

Funny though that CORS gets triggered for file://mogzbox/Users/ggrossetie/Downloads/test.adoc and not for file://c:\Users/ggrossetie/Downloads/test.adoc

Thanks for the debugging.

**Comment by sysfu** [comment]
I'm getting this error, will open a new issue "DevTools failed to load SourceMap: Could not load content for chrome-extension://iaalpfgpbocpdfblpnhhgllgbdbchmia/js/vendor/chartist.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME"
